# $HOME/.config/alacritty/alacritty.toml

# Alacritty now uses TOML formatting for its config files.

[window]

opacity = 0.8

padding.x = 10
padding.y = 10
dynamic_padding = true

decorations = "Full"
decorations_theme_variant = "Dark"#"Light"
blur = true

[font]

normal.family = "JetBrainsMonoNerdFont"
bold.family = "JetBrainsMonoNerdFont"
italic.family = "JetBrainsMonoNerdFont"
bold_italic.family = "JetBrainsMonoNerdFont"

size = 11.25

[scrolling]

history = 10000

multiplier = 3

[colors]
[colors.primary]
foreground = "#f0f3f6"

background = "#0a0c10"
dim_foreground = "#828482"

[colors.cursor] 
text = "#0a0c10"
cursor = "#f0f3f6"

[colors.normal]
black = "#7a828e"

red = "#ff9492"

green = "#26cd4d"

yellow = "#f0b72f"

blue = "#71b7ff"

magenta = "#cb9eff"

cyan = "#39c5cf"

white = "#d9dee3"


[colors.bright]
black = "#9ea7b3"

red = "#ffb1af"

green = "#4ae168"

yellow = "#f7c843"

blue = "#91cbff"

magenta = "#cb9eff"

cyan = "#39c5cf"

white = "#d9dee3"
